# Generated by Django 5.1.7 on 2025-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
