# Generated by Django 5.1.7 on 2025-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_images/'),
        ),
    ]
